// Localidades de la provincia de Córdoba (Argentina), orden alfabético.
// Fuente: INDEC, censo 2022 (vía Wikipedia - Anexo:Localidades de la
// Provincia de Córdoba). Se usa para el combo de localidad de /solicitar,
// que fija la provincia en Córdoba.
export const LOCALIDADES_CORDOBA = [
  'Achiras', 'Adelia María', 'Agua de Oro', 'Alcira Gigena', 'Aldea Santa María',
  'Alejandro Roca', 'Alejo Ledesma', 'Alicia', 'Almafuerte', 'Alpa Corral',
  'Alta Gracia', 'Alto Alegre', 'Alto de los Quebrachos', 'Altos de Chipión', 'Amboy',
  'Ambul', 'Ana Zumarán', 'Anisacate', 'Arias', 'Arroyito',
  'Arroyo Algodón', 'Arroyo Cabral', 'Arroyo de Los Patos', 'Assunta', 'Atahona',
  'Ausonia', 'Avellaneda', 'Ballesteros', 'Ballesteros Sud', 'Balnearia',
  'Bañado de Soto', 'Bell Ville', 'Bengolea', 'Benjamín Gould', 'Berrotarán',
  'Bialet Massé', 'Bouwer', 'Brinkmann', 'Buchardo', 'Bulnes',
  'Cabalango', 'Calchín', 'Calchín Oeste', 'Camilo Aldao', 'Caminiaga',
  'Canals', 'Candelaria Sud', 'Cañada de Luque', 'Cañada de Machado', 'Cañada de Río Pinto',
  'Cañada del Sauce', 'Capilla de los Remedios', 'Capilla de Sitón', 'Capilla del Carmen', 'Capilla del Monte',
  "Capitán General Bernardo O'Higgins", 'Carnerillo', 'Carrilobo', 'Casa Grande', 'Cavanagh',
  'Cerro Colorado', 'Chaján', 'Chalacea', 'Chancani', 'Chañar Viejo',
  'Charbonier', 'Charras', 'Chazón', 'Chilibroste', 'Chucul',
  'Chuña', 'Chuña Huasi', 'Churqui Cañada', 'Ciénaga del Coro', 'Cintra',
  'Colazo', 'Colonia Almada', 'Colonia Anita', 'Colonia Barge', 'Colonia Bismarck',
  'Colonia Bremen', 'Colonia Caroya', 'Colonia Italiana', 'Colonia Iturraspe', 'Colonia Las Cuatro Esquinas',
  'Colonia Las Pichanas', 'Colonia Marina', 'Colonia Prosperidad', 'Colonia San Bartolomé', 'Colonia San Pedro',
  'Colonia Tirolesa', 'Colonia Valtelina', 'Colonia Vicente Agüero', 'Colonia Videla', 'Colonia Vignaud',
  'Comechingones', 'Conlara', 'Copacabana', 'Córdoba', 'Coronel Baigorria',
  'Coronel Moldes', 'Corral de Bustos Ifflinger', 'Corralito', 'Cosquín', 'Costa Sacate',
  'Cruz Alta', 'Cruz de Caña', 'Cruz del Eje', 'Cuesta Blanca', 'Dalmacio Vélez',
  'Deán Funes', 'Del Campillo', 'Despeñaderos', 'Devoto', 'Diego de Rojas',
  'Dique Chico', 'El Arañado', 'El Brete', 'El Chacho', 'El Crispín',
  'El Fortín', 'El Manzano', 'El Rastreador', 'El Rodeo', 'El Tío',
  'Elena', 'Embalse', 'Esquina', 'Estación General Paz', 'Estación Juárez Celman',
  'Estancia de Guadalupe', 'Estancia Vieja', 'Etruria', 'Eufrasio Loza', 'Falda del Carmen',
  'Freyre', 'General Baldissera', 'General Cabrera', 'General Deheza', 'General Fotheringham',
  'General Levalle', 'General Roca', 'Guanaco Muerto', 'Guasapampa', 'Guatimozín',
  'Gutemberg', 'Hernando', 'Huanchilla', 'Huerta Grande', 'Huinca Renancó',
  'Idiazábal', 'Impira', 'Inriville', 'Isla Verde', 'Italó',
  'James Craik', 'Jesús María', 'Jovita', 'Justiniano Posse', 'Kilómetro 658',
  'La Batea', 'La Calera', 'La Carlota', 'La Carolina El Potosí', 'La Cautiva',
  'La Cesira', 'La Cruz', 'La Cumbre', 'La Cumbrecita', 'La Falda',
  'La Francia', 'La Granja', 'La Higuera', 'La Laguna', 'La Paisanita',
  'La Palestina', 'La Pampa', 'La Paquita', 'La Para', 'La Paz',
  'La Playa', 'La Playosa', 'La Población', 'La Posta', 'La Puerta (Río Primero)',
  'La Quinta', 'La Rancherita', 'La Rinconada', 'La Serranita', 'La Tordilla',
  'Laborde', 'Laboulaye', 'Laguna Larga', 'Las Acequias', 'Las Albahacas',
  'Las Arrias', 'Las Bajadas', 'Las Caleras', 'Las Calles', 'Las Cañadas',
  'Las Gramillas', 'Las Higueras', 'Las Isletillas', 'Las Junturas', 'Las Palmas',
  'Las Peñas', 'Las Peñas Sud', 'Las Perdices', 'Las Playas', 'Las Rabonas',
  'Las Saladas', 'Las Tapias', 'Las Varas', 'Las Varillas', 'Las Vertientes',
  'Leguizamón', 'Leones', 'Los Cedros', 'Los Cerrillos', 'Los Chañaritos (Cruz del Eje-Ischilín)',
  'Los Chañaritos (Río Segundo)', 'Los Cisnes', 'Los Cocos', 'Los Cóndores', 'Los Hornillos',
  'Los Hoyos', 'Los Mistoles', 'Los Molinos', 'Los Pozos', 'Los Reartes',
  'Los Surgentes', 'Los Talares', 'Los Zorros', 'Lozada', 'Luca',
  'Lucio Victorio Mansilla', 'Luque', 'Lutti', 'Luyaba', 'Malagueño',
  'Malena', 'Malvinas Argentinas', 'Manfredi', 'Maquinista Gallini', 'Marcos Juárez',
  'Marull', 'Matorrales', 'Mattaldi', 'Mayu Sumaj', 'Media Naranja',
  'Melo', 'Mendiolaza', 'Mi Granja', 'Mina Clavero', 'Miramar de Ansenuza',
  'Monte Buey', 'Monte de los Gauchos', 'Monte Leña', 'Monte Maíz', 'Monte Ralo',
  'Montecristo', 'Morrison', 'Morteros', 'Nicolás Bruzzone', 'Noetinger',
  'Nono', 'Obispo Trejo', 'Olaeta', 'Oliva', 'Olivares de San Nicolás',
  'Onagoity', 'Oncativo', 'Ordóñez', 'Pacheco de Melo', 'Pampayasta Norte',
  'Pampayasta Sud', 'Panaholma', 'Parque Calmayo', 'Pascanas', 'Pasco',
  'Paso del Durazno', 'Paso Viejo', 'Pilar', 'Pincén', 'Piquillín',
  'Plaza de Mercedes', 'Plaza Luxardo', 'Porteña', 'Potrero de Garay', 'Pozo del Molle',
  'Pozo Nuevo', 'Pueblo Italiano', 'Puesto de Castro', 'Punta del Agua', 'Quebracho Herrado',
  'Quilino', 'Rafael García', 'Ranqueles', 'Rayo Cortado', 'Reducción',
  'Rincón', 'Río Bamba', 'Río Ceballos', 'Río Cuarto', 'Río de los Sauces',
  'Río Primero', 'Río Segundo', 'Río Tercero', 'Rosales', 'Rosario del Saladillo',
  'Sacanta', 'Sagrada Familia', 'Saira', 'Saladillo', 'Saldán',
  'Salsacate', 'Salsipuedes', 'Sampacho', 'San Agustín', 'San Antonio de Arredondo',
  'San Antonio de Litín', 'San Basilio', 'San Carlos Minas', 'San Clemente', 'San Esteban',
  'San Francisco', 'San Francisco del Chañar', 'San Gerónimo', 'San Ignacio', 'San Javier y Yacanto',
  'San Joaquín', 'San José', 'San José de la Dormida', 'San José de las Salinas', 'San Lorenzo',
  'San Marcos Sierra', 'San Marcos Sud', 'San Pedro', 'San Pedro Norte', 'San Roque',
  'San Vicente', 'Santa Catalina Holmberg', 'Santa Elena', 'Santa Eufemia', 'Santa María de Punilla',
  'Santa Rosa de Calamuchita', 'Santa Rosa de Río Primero', 'Santiago Temple', 'Sarmiento', 'Saturnino María Laspiur',
  'Sauce Arriba', 'Sebastián Elcano', 'Seeber', 'Segunda Usina', 'Serrano',
  'Serrezuela', 'Silvio Pellico', 'Simbolar', 'Sinsacate', 'Suco',
  'Tala Cañada', 'Tala Huasi', 'Talaini', 'Tancacha', 'Tanti',
  'Ticino', 'Tinoco', 'Tío Pujio', 'Toledo', 'Toro Pujio',
  'Tosno', 'Tosquita', 'Tránsito', 'Tuclame', 'Ucacha',
  'Unquillo', 'Valle de Anisacate', 'Valle Hermoso', 'Viamonte', 'Vicuña Mackenna',
  'Villa Allende', 'Villa Amancay', 'Villa Ascasubi', 'Villa Candelaria Norte', 'Villa Carlos Paz',
  'Villa Cerro Azul', 'Villa Ciudad de América', 'Villa Ciudad Parque Los Reartes', 'Villa Concepción del Tío', 'Villa Cura Brochero',
  'Villa de las Rosas', 'Villa de María', 'Villa de Pocho', 'Villa de Soto', 'Villa del Dique',
  'Villa del Prado', 'Villa del Rosario', 'Villa del Totoral', 'Villa Dolores', 'Villa El Chacay',
  'Villa Elisa', 'Villa Fontana', 'Villa General Belgrano', 'Villa Giardino', 'Villa Gutiérrez',
  'Villa Huidobro', 'Villa La Bolsa', 'Villa Los Aromos', 'Villa Los Patos', 'Villa María',
  'Villa Nueva', 'Villa Parque Santa Ana', 'Villa Parque Síquiman', 'Villa Quillinzo', 'Villa Río Icho Cruz',
  'Villa Rossi', 'Villa Rumipal', 'Villa San Esteban', 'Villa San Isidro', 'Villa Santa Cruz del Lago',
  'Villa Sarmiento', 'Villa Tulumba', 'Villa Valeria', 'Villa Yacanto', 'Washington',
  'Wenceslao Escalante',
]
