[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/bcra-deudas"
  to = "/.netlify/functions/bcra-deudas"
  status = 200

[[redirects]]
  from = "/api/bcra-cheques"
  to = "/.netlify/functions/bcra-cheques"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
